export const userActionsConstants = {
    SEARCH_FOR_SHOW_REQUEST: "SEARCH_FOR_SHOW_REQUEST",
    SEARCH_FOR_SHOW_SUCCESS: "SEARCH_FOR_SHOW_SUCCESS",
    SEARCH_FOR_SHOW_FAILURE: "SEARCH_FOR_SHOW_FAILURE",

    ADD_SHOW_TO_LIST_REQUEST: "ADD_SHOW_TO_LIST_REQUEST",
    ADD_SHOW_TO_LIST_SUCCESS: "ADD_SHOW_TO_LIST_SUCCESS",
    ADD_SHOW_TO_LIST_FAILURE: "ADD_SHOW_TO_LIST_FAILURE",

    GET_EPISODE_INFO_REQUEST: "GET_EPISODE_INFO_REQUEST",
    GET_EPISODE_INFO_SUCCESS: "GET_EPISODE_INFO_SUCCESS",
    GET_EPISODE_INFO_FAILURE: "GET_EPISODE_INFO_FAILURE",

    UPDATE_EPISODE_LIST_REQUEST: "ADD_EPISODE_TO_WATCHLIST_REQUEST",
    UPDATE_EPISODE_LIST_SUCCESS: "ADD_EPISODE_TO_WATCHLIST_SUCCESSS",
    UPDATE_EPISODE_LIST_FAILURE: "ADD_EPISODE_TO_WATCHLIST_FAILURE",

    REMOVE_SHOW_FROM_LIST_REQUEST: "REMOVE_SHOW_FROM_LIST_REQUEST",
    REMOVE_SHOW_FROM_LIST_SUCCESS: "REMOVE_SHOW_FROM_LIST_SUCCESS",
    REMOVE_SHOW_FROM_LIST_FAILURE: "REMOVE_SHOW_FROM_LIST_FAILURE",

    TOGGLE_NEW_EPISODE_NOTIFICATION_REQUEST: "TOGGLE_NEW_EPISODE_NOTIFICATION_REQUEST",
    TOGGLE_NEW_EPISODE_NOTIFICATION_SUCCESS: "TOGGLE_NEW_EPISODE_NOTIFICATION_SUCCESS",
    TOGGLE_NEW_EPISODE_NOTIFICATION_FAILURE: "TOGGLE_NEW_EPISODE_NOTIFICATION_FAILURE",

    UPDATE_INFO_REQUEST: "UPDATE_EMAIL_ADDRESS_REQUEST",
    UPDATE_INFO_SUCCESS: "UPDATE_EMAIL_ADDRESS_SUCESS",
    UPDATE_INFO_FAILURE: "UPDATE_EMAIL_ADDRESS_FAILURE",

    SEND_FEEDBACK_REQUEST: "SEND_FEEDBACK_REQUEST",
    SEND_FEEDBACK_SUCCESS: "SEND_FEEDBACK_SUCCESS",
    SEND_FEEDBACK_FAILURE: "SEND_FEEDBACK_FAILURE",

    DELETE_ACCOUNT_REQUEST: "DELETE_ACCOUNT_REQUEST",
    DELETE_ACCOUNT_SUCCESS: "DELETE_ACCOUNT_SUCCESS",
    DELETE_ACCOUNT_FAILURE: "DELETE_ACCOUNT_FAILURE"

}