export const authenticationConstants = {
    SIGNUP_REQUEST: "SIGNUP_REQUEST",
    SIGNUP_SUCCESS: "SIGNUP_SUCCESS",
    SIGNUP_FAILURE: "SIGNUP_FAILURE",
  
    SIGNIN_REQUEST: "SIGNIN_REQUEST",
    SIGNIN_SUCCESS: "SIGNIN_REQUEST",
    SIGNIN_FAILURE: "SIGNIN_FAILURE",
  
    FORGOT_PASSWORD_REQUEST: "FORGOT_PASSWORD_REQUEST",
    FORGOT_PASSWORD_SUCCESS: "FORGOT_PASSWORD_SUCCESS",
    FORGOT_PASSWORD_FAILURE: "FORGOT_PASSWORD_FAILURE",
  
    CHECK_SECURITY_ANSWER_REQUEST: "CHECK_SECURITY_ANSWER_REQUEST",
    CHECK_SECURITY_ANSWER_SUCCESS: "CHECK_SECURITY_ANSWER_SUCCESS",
    CHECK_SECURITY_ANSWER_FAILURE: "CHECK_SECURITY_ANSWER_FAILURE",
  
    SIGNOUT_REQUEST: "SIGNOUT_REQUEST",
    SIGNOUT_SUCCESS: "SIGNOUT_SUCCESS",
    SIGNOUT_FAILURE: "SIGNOUT_FAILURE" 
  }